version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 14
    pre_build:
        commands:
            - echo "================= INSTALLING DEPENDENCIES ================="
            - npm install
            - echo "================= RUNNING LINT ================="
            - npm run lint
    build:
        commands:
            - echo "================= BUILDING ================="
            - npm run build
            - echo "================= CREATING CLOUD FORMATION SERVICE STACK ================="
            - export BUCKET=candleapp-develop-releases
            - aws cloudformation package --template-file template.develop.yml --s3-bucket $BUCKET --output-template-file packaged.develop.yml
artifacts:
    type: zip
    files:
        - template.develop.yml
        - packaged.develop.yml